#!/bin/bash

#program to output a system information page

TITLE="System Info Report for $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIMESTAMP="Generated $CURRENT_TIME, by $USER'

echo "<HTML>"
echo "	<HEAD>"
echo "		<TITLE>$TitLE</TITLE>"
echo "	</HEAD>"
echo "	<BODY>"
echo "		<H1>$TITLE</H1>"
echo "		<P>$TIMESTAMP</P>"
echo "	</BODY>"
echo "</HTML>"
